# GENERATED by sdk/build.py from openapi.json v1.5.8 — do not edit by hand.
"""Every Mind Upload partner API operation, one typed method each."""
from typing import Any, Dict, List, Optional

from ._client import Result, _BaseClient


class MindUpload(_BaseClient):
    """Client for the Mind Upload partner API.

    Create one with your partner key, then call any operation. Every method
    returns a :class:`Result` (attribute + dict access) and raises a
    :class:`~mindupload.MindUploadError` subclass on failure.
    """

    # --- AI Consciousnesses ------------------------------------------------
    def create_clone(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None, nickname: Optional[str] = None, gender: Optional[str] = None, avatar_id: Optional[str] = None, accept_chatroom_invitation_by_others: Optional[bool] = None) -> Result:
        """Create a new AI consciousness for the user.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.
            nickname: See the full parameter reference.
            gender: See the full parameter reference.
            avatar_id: See the full parameter reference.
            accept_chatroom_invitation_by_others: See the full parameter reference.

        Returns:
            Result fields: success, error_message.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("create_clone", {"preferred_language": preferred_language, "username": username, "password": password, "codename": codename, "nickname": nickname, "gender": gender, "avatar_id": avatar_id, "accept_chatroom_invitation_by_others": accept_chatroom_invitation_by_others})

    def get_clones(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None) -> Result:
        """List the user's AI consciousnesses.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.

        Returns:
            Result fields: success, error_message, clones.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_clones", {"preferred_language": preferred_language, "username": username, "password": password})

    def update_clone(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None, nickname: Optional[str] = None, gender: Optional[str] = None, avatar_id: Optional[str] = None, accept_chatroom_invitation_by_others: Optional[bool] = None) -> Result:
        """Update an AI consciousness's profile.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.
            nickname: See the full parameter reference.
            gender: See the full parameter reference.
            avatar_id: See the full parameter reference.
            accept_chatroom_invitation_by_others: See the full parameter reference.

        Returns:
            Result fields: success, error_message.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("update_clone", {"preferred_language": preferred_language, "username": username, "password": password, "codename": codename, "nickname": nickname, "gender": gender, "avatar_id": avatar_id, "accept_chatroom_invitation_by_others": accept_chatroom_invitation_by_others})

    # --- Account -----------------------------------------------------------
    def get_quota(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None) -> Result:
        """Check your partner API rate limits, credit caps, and current usage.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.

        Returns:
            Result fields: success, error_message, per_user_rate_limit_per_min, per_user_daily_credit_cap, partner_rate_limit_per_min, partner_daily_credit_cap, max_users, registered_users, partner_requests_last_minute, partner_credit_spends_last_day, user, user_requests_last_minute, user_credit_spends_last_day, credit_spending_tasks, operation_duration_ms.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_quota", {"preferred_language": preferred_language, "username": username})

    # --- Authentication ----------------------------------------------------
    def check_username(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None) -> Result:
        """Check whether a username is still available before registering.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.

        Returns:
            Result fields: success, error_message, exists, disabled, rate_limited, flood_window, wait_seconds, operation_duration_ms.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("check_username", {"preferred_language": preferred_language, "username": username})

    def login(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None) -> Result:
        """Sign a user in and receive a session token (JWT) for subsequent calls.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.

        Returns:
            Result fields: success, error_message, jwt, decrypted_user.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("login", {"preferred_language": preferred_language, "username": username, "password": password})

    def logout(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None) -> Result:
        """End the current user session.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.

        Returns:
            Result fields: success, error_message, revoked, operation_duration_ms.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("logout", {"preferred_language": preferred_language, "username": username, "password": password})

    def register(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, email: Optional[str] = None, email_verification_code: Optional[str] = None, first_name: Optional[str] = None, last_name: Optional[str] = None, nickname: Optional[str] = None, gender: Optional[str] = None, birth_date: Optional[int] = None, phone_number: Optional[str] = None, avatar_id: Optional[str] = None, accept_chatroom_invitation_by_others: Optional[bool] = None) -> Result:
        """Create a user account on your platform.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            email: See the full parameter reference.
            email_verification_code: See the full parameter reference.
            first_name: See the full parameter reference.
            last_name: See the full parameter reference.
            nickname: See the full parameter reference.
            gender: See the full parameter reference.
            birth_date: See the full parameter reference.
            phone_number: See the full parameter reference.
            avatar_id: See the full parameter reference.
            accept_chatroom_invitation_by_others: See the full parameter reference.

        Returns:
            Result fields: success, error_message, jwt, decrypted_user.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("register", {"preferred_language": preferred_language, "username": username, "password": password, "email": email, "email_verification_code": email_verification_code, "first_name": first_name, "last_name": last_name, "nickname": nickname, "gender": gender, "birth_date": birth_date, "phone_number": phone_number, "avatar_id": avatar_id, "accept_chatroom_invitation_by_others": accept_chatroom_invitation_by_others})

    # --- Chatrooms ---------------------------------------------------------
    def check_chatroom_updates(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatrooms: Optional[List[Dict[str, Any]]] = None) -> Result:
        """Cheaply poll whether the user's chatrooms have new activity.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatrooms: Rooms to check. Each entry must include `chatroom_id`; include `known_updated_at` from the previous response, or null/omit it on the first poll.

        Returns:
            Result fields: success, error_message, server_time, poll_config, chatrooms.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("check_chatroom_updates", {"preferred_language": preferred_language, "username": username, "password": password, "chatrooms": chatrooms})

    def create_chatroom(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatroom_name: Optional[str] = None, is_public: Optional[bool] = None, avatar_id: Optional[str] = None, soulmate_check_enabled: Optional[bool] = None) -> Result:
        """Create a chatroom.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatroom_name: See the full parameter reference.
            is_public: See the full parameter reference.
            avatar_id: See the full parameter reference.
            soulmate_check_enabled: See the full parameter reference.

        Returns:
            Result fields: success, error_message, chatroom_id.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("create_chatroom", {"preferred_language": preferred_language, "username": username, "password": password, "chatroom_name": chatroom_name, "is_public": is_public, "avatar_id": avatar_id, "soulmate_check_enabled": soulmate_check_enabled})

    def create_chatroom_membership(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatroom_id: Optional[str] = None, invitee_username: Optional[str] = None, invitee_codename: Optional[str] = None, admin_level: Optional[str] = None) -> Result:
        """Invite a user or an AI consciousness into a chatroom.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatroom_id: Chatroom id as returned by chatroom operations.
            invitee_username: See the full parameter reference.
            invitee_codename: See the full parameter reference.
            admin_level: See the full parameter reference.

        Returns:
            Result fields: success, error_message, membership_id.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("create_chatroom_membership", {"preferred_language": preferred_language, "username": username, "password": password, "chatroom_id": chatroom_id, "invitee_username": invitee_username, "invitee_codename": invitee_codename, "admin_level": admin_level})

    def create_chatroom_message(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatroom_id: Optional[str] = None, text: Optional[str] = None) -> Result:
        """Send a message to a chatroom.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatroom_id: Chatroom id as returned by chatroom operations.
            text: See the full parameter reference.

        Returns:
            Result fields: success, error_message, message_id.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("create_chatroom_message", {"preferred_language": preferred_language, "username": username, "password": password, "chatroom_id": chatroom_id, "text": text})

    def get_chatroom_membership(self, *, preferred_language: Optional[str] = None, page: Optional[int] = None, page_size: Optional[int] = None, sort_by: Optional[str] = None, sort_order: Optional[int] = None, use_cursor_pagination: Optional[bool] = None, cursor_value: Optional[str] = None, cursor_id: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatroom_id: Optional[str] = None) -> Result:
        """List the members of a chatroom the user belongs to.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            page: See the full parameter reference.
            page_size: See the full parameter reference.
            sort_by: See the full parameter reference.
            sort_order: See the full parameter reference.
            use_cursor_pagination: See the full parameter reference.
            cursor_value: See the full parameter reference.
            cursor_id: See the full parameter reference.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatroom_id: Chatroom id as returned by chatroom operations.

        Returns:
            Result fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, memberships.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_chatroom_membership", {"preferred_language": preferred_language, "page": page, "page_size": page_size, "sort_by": sort_by, "sort_order": sort_order, "use_cursor_pagination": use_cursor_pagination, "cursor_value": cursor_value, "cursor_id": cursor_id, "username": username, "password": password, "chatroom_id": chatroom_id})

    def get_chatroom_messages(self, *, preferred_language: Optional[str] = None, page: Optional[int] = None, page_size: Optional[int] = None, sort_by: Optional[str] = None, sort_order: Optional[int] = None, use_cursor_pagination: Optional[bool] = None, cursor_value: Optional[str] = None, cursor_id: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatroom_id: Optional[str] = None, since_value: Optional[float] = None, since_id: Optional[str] = None) -> Result:
        """Fetch messages from a chatroom the user belongs to.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            page: See the full parameter reference.
            page_size: See the full parameter reference.
            sort_by: See the full parameter reference.
            sort_order: See the full parameter reference.
            use_cursor_pagination: See the full parameter reference.
            cursor_value: See the full parameter reference.
            cursor_id: See the full parameter reference.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatroom_id: Chatroom id as returned by chatroom operations.
            since_value: See the full parameter reference.
            since_id: See the full parameter reference.

        Returns:
            Result fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, messages, media_thumbnails, since_overflow.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_chatroom_messages", {"preferred_language": preferred_language, "page": page, "page_size": page_size, "sort_by": sort_by, "sort_order": sort_order, "use_cursor_pagination": use_cursor_pagination, "cursor_value": cursor_value, "cursor_id": cursor_id, "username": username, "password": password, "chatroom_id": chatroom_id, "since_value": since_value, "since_id": since_id})

    def get_chatrooms(self, *, preferred_language: Optional[str] = None, page: Optional[int] = None, page_size: Optional[int] = None, sort_by: Optional[str] = None, sort_order: Optional[int] = None, use_cursor_pagination: Optional[bool] = None, cursor_value: Optional[str] = None, cursor_id: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, get_public: Optional[bool] = None, get_private: Optional[bool] = None) -> Result:
        """List the chatrooms the user belongs to.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            page: See the full parameter reference.
            page_size: See the full parameter reference.
            sort_by: See the full parameter reference.
            sort_order: See the full parameter reference.
            use_cursor_pagination: See the full parameter reference.
            cursor_value: See the full parameter reference.
            cursor_id: See the full parameter reference.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            get_public: See the full parameter reference.
            get_private: See the full parameter reference.

        Returns:
            Result fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chatrooms.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_chatrooms", {"preferred_language": preferred_language, "page": page, "page_size": page_size, "sort_by": sort_by, "sort_order": sort_order, "use_cursor_pagination": use_cursor_pagination, "cursor_value": cursor_value, "cursor_id": cursor_id, "username": username, "password": password, "get_public": get_public, "get_private": get_private})

    def translate_chatroom_message(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, chatroom_id: Optional[str] = None, message_id: Optional[str] = None) -> Result:
        """Translate a text chatroom message into the viewer language.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            chatroom_id: Chatroom id as returned by chatroom operations.
            message_id: Chatroom message id.

        Returns:
            Result fields: success, error_message, translated_text, target_language, cached.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("translate_chatroom_message", {"preferred_language": preferred_language, "username": username, "password": password, "chatroom_id": chatroom_id, "message_id": message_id})

    # --- Conversation ------------------------------------------------------
    def get_chat(self, *, preferred_language: Optional[str] = None, page: Optional[int] = None, page_size: Optional[int] = None, sort_by: Optional[str] = None, sort_order: Optional[int] = None, use_cursor_pagination: Optional[bool] = None, cursor_value: Optional[str] = None, cursor_id: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None) -> Result:
        """Fetch the one-on-one conversation history with an AI consciousness.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            page: See the full parameter reference.
            page_size: See the full parameter reference.
            sort_by: See the full parameter reference.
            sort_order: See the full parameter reference.
            use_cursor_pagination: See the full parameter reference.
            cursor_value: See the full parameter reference.
            cursor_id: See the full parameter reference.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.

        Returns:
            Result fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chats, media_thumbnails.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_chat", {"preferred_language": preferred_language, "page": page, "page_size": page_size, "sort_by": sort_by, "sort_order": sort_order, "use_cursor_pagination": use_cursor_pagination, "cursor_value": cursor_value, "cursor_id": cursor_id, "username": username, "password": password, "codename": codename})

    def rag(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None, text: Optional[str] = None, chatroom_id: Optional[str] = None) -> Result:
        """Send a message to an AI consciousness and receive its reply.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.
            text: See the full parameter reference.
            chatroom_id: Chatroom id as returned by chatroom operations.

        Returns:
            Result fields: success, error_message, response_text, clone_nickname, consolidation_summary, consolidation_count, consolidation_dispatched.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("rag", {"preferred_language": preferred_language, "username": username, "password": password, "codename": codename, "text": text, "chatroom_id": chatroom_id})

    def trigger_social(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, membership_id: Optional[str] = None, chatroom_id: Optional[str] = None) -> Result:
        """Have an AI consciousness proactively join the conversation in a chatroom.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            membership_id: See the full parameter reference.
            chatroom_id: Chatroom id as returned by chatroom operations.

        Returns:
            Result fields: success, error_message, response_text, chatroom_digests_count, chatroom_digests_summary, consolidation_summary, consolidation_count, consolidation_dispatched.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("trigger_social", {"preferred_language": preferred_language, "username": username, "password": password, "membership_id": membership_id, "chatroom_id": chatroom_id})

    # --- Insights ----------------------------------------------------------
    def get_mind_cluster(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None, node_id: Optional[str] = None, texts_offset: Optional[int] = None, texts_page_size: Optional[int] = None, force_rebuild: Optional[bool] = None) -> Result:
        """Fetch the mind-graph visualization data of an AI consciousness.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.
            node_id: See the full parameter reference.
            texts_offset: See the full parameter reference.
            texts_page_size: See the full parameter reference.
            force_rebuild: See the full parameter reference.

        Returns:
            Result fields: success, error_message, root_node_id, node, children, texts, total_texts, texts_offset, has_more_texts, is_building.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_mind_cluster", {"preferred_language": preferred_language, "username": username, "password": password, "codename": codename, "node_id": node_id, "texts_offset": texts_offset, "texts_page_size": texts_page_size, "force_rebuild": force_rebuild})

    def get_soulmate_report(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, my_clone_id: Optional[str] = None, other_clone_id: Optional[str] = None, chatroom_id: Optional[str] = None) -> Result:
        """Generate or fetch the compatibility report between two chatroom members.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            my_clone_id: See the full parameter reference.
            other_clone_id: See the full parameter reference.
            chatroom_id: Chatroom id as returned by chatroom operations.

        Returns:
            Result fields: success, error_message, report, report_generated_at, is_generating, charged.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_soulmate_report", {"preferred_language": preferred_language, "username": username, "password": password, "my_clone_id": my_clone_id, "other_clone_id": other_clone_id, "chatroom_id": chatroom_id})

    # --- Media -------------------------------------------------------------
    def abort_multipart_upload(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, r2_key: Optional[str] = None, upload_id: Optional[str] = None) -> Result:
        """Cancel a multipart upload and discard its parts.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            r2_key: Opaque media object key returned by upload-start operations and reused for multipart upload calls.
            upload_id: Multipart upload session id returned by `request_multipart_upload`.

        Returns:
            Result fields: success, error_message.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("abort_multipart_upload", {"preferred_language": preferred_language, "username": username, "password": password, "r2_key": r2_key, "upload_id": upload_id})

    def cancel_upload(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, r2_key: Optional[str] = None) -> Result:
        """Cancel a pending upload.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            r2_key: Opaque media object key returned by upload-start operations and reused for multipart upload calls.

        Returns:
            Result fields: success, error_message.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("cancel_upload", {"preferred_language": preferred_language, "username": username, "password": password, "r2_key": r2_key})

    def complete_multipart_upload(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, r2_key: Optional[str] = None, upload_id: Optional[str] = None, parts: Optional[List[Dict[str, Any]]] = None) -> Result:
        """Finish a multipart upload.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            r2_key: Opaque media object key returned by upload-start operations and reused for multipart upload calls.
            upload_id: Multipart upload session id returned by `request_multipart_upload`.
            parts: The successfully uploaded parts, using the `part_number` and `etag` returned by each part upload.

        Returns:
            Result fields: success, error_message, media_url.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("complete_multipart_upload", {"preferred_language": preferred_language, "username": username, "password": password, "r2_key": r2_key, "upload_id": upload_id, "parts": parts})

    def list_upload_parts(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, r2_key: Optional[str] = None, upload_id: Optional[str] = None) -> Result:
        """List the parts already uploaded in a multipart upload.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            r2_key: Opaque media object key returned by upload-start operations and reused for multipart upload calls.
            upload_id: Multipart upload session id returned by `request_multipart_upload`.

        Returns:
            Result fields: success, error_message, parts.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("list_upload_parts", {"preferred_language": preferred_language, "username": username, "password": password, "r2_key": r2_key, "upload_id": upload_id})

    def request_multipart_upload(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, filename: Optional[str] = None, content_type: Optional[str] = None, file_size_bytes: Optional[int] = None, media_type: Optional[str] = None, has_thumbnail: Optional[bool] = None) -> Result:
        """Start a large-file upload in multiple parts.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            filename: See the full parameter reference.
            content_type: See the full parameter reference.
            file_size_bytes: See the full parameter reference.
            media_type: See the full parameter reference.
            has_thumbnail: See the full parameter reference.

        Returns:
            Result fields: success, error_message, upload_id, r2_key, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("request_multipart_upload", {"preferred_language": preferred_language, "username": username, "password": password, "filename": filename, "content_type": content_type, "file_size_bytes": file_size_bytes, "media_type": media_type, "has_thumbnail": has_thumbnail})

    def request_upload_url(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, filename: Optional[str] = None, content_type: Optional[str] = None, file_size_bytes: Optional[int] = None, media_type: Optional[str] = None, has_thumbnail: Optional[bool] = None) -> Result:
        """Request an upload slot and a signed viewing link for a media attachment.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            filename: See the full parameter reference.
            content_type: See the full parameter reference.
            file_size_bytes: See the full parameter reference.
            media_type: See the full parameter reference.
            has_thumbnail: See the full parameter reference.

        Returns:
            Result fields: success, error_message, r2_key, presigned_url, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("request_upload_url", {"preferred_language": preferred_language, "username": username, "password": password, "filename": filename, "content_type": content_type, "file_size_bytes": file_size_bytes, "media_type": media_type, "has_thumbnail": has_thumbnail})

    def sign_upload_part(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, r2_key: Optional[str] = None, upload_id: Optional[str] = None, part_number: Optional[int] = None) -> Result:
        """Get the signed link for one part of a multipart upload.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            r2_key: Opaque media object key returned by upload-start operations and reused for multipart upload calls.
            upload_id: Multipart upload session id returned by `request_multipart_upload`.
            part_number: One-based multipart part number.

        Returns:
            Result fields: success, error_message, presigned_url.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("sign_upload_part", {"preferred_language": preferred_language, "username": username, "password": password, "r2_key": r2_key, "upload_id": upload_id, "part_number": part_number})

    def sign_upload_parts_batch(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, r2_key: Optional[str] = None, upload_id: Optional[str] = None, part_numbers: Optional[List[int]] = None) -> Result:
        """Get signed links for several parts of a multipart upload at once.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            r2_key: Opaque media object key returned by upload-start operations and reused for multipart upload calls.
            upload_id: Multipart upload session id returned by `request_multipart_upload`.
            part_numbers: One-based multipart part numbers to sign in a single batch.

        Returns:
            Result fields: success, error_message, presigned_urls.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("sign_upload_parts_batch", {"preferred_language": preferred_language, "username": username, "password": password, "r2_key": r2_key, "upload_id": upload_id, "part_numbers": part_numbers})

    # --- Memories ----------------------------------------------------------
    def create_text(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None, clone_id: Optional[str] = None, text: Optional[str] = None, type: Optional[str] = None) -> Result:
        """Upload a memory or persona entry to an AI consciousness.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.
            clone_id: See the full parameter reference.
            text: See the full parameter reference.
            type: See the full parameter reference.

        Returns:
            Result fields: success, error_message, cluster_label, cluster_modified_count.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("create_text", {"preferred_language": preferred_language, "username": username, "password": password, "codename": codename, "clone_id": clone_id, "text": text, "type": type})

    def get_texts(self, *, preferred_language: Optional[str] = None, page: Optional[int] = None, page_size: Optional[int] = None, sort_by: Optional[str] = None, sort_order: Optional[int] = None, use_cursor_pagination: Optional[bool] = None, cursor_value: Optional[str] = None, cursor_id: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, codename: Optional[str] = None, type: Optional[str] = None) -> Result:
        """List the memories and persona entries uploaded to an AI consciousness.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            page: See the full parameter reference.
            page_size: See the full parameter reference.
            sort_by: See the full parameter reference.
            sort_order: See the full parameter reference.
            use_cursor_pagination: See the full parameter reference.
            cursor_value: See the full parameter reference.
            cursor_id: See the full parameter reference.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            codename: See the full parameter reference.
            type: See the full parameter reference.

        Returns:
            Result fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, texts.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_texts", {"preferred_language": preferred_language, "page": page, "page_size": page_size, "sort_by": sort_by, "sort_order": sort_order, "use_cursor_pagination": use_cursor_pagination, "cursor_value": cursor_value, "cursor_id": cursor_id, "username": username, "password": password, "codename": codename, "type": type})

    # --- Users -------------------------------------------------------------
    def get_user(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None) -> Result:
        """Fetch the signed-in user's profile.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.

        Returns:
            Result fields: success, error_message, jwt, decrypted_user.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("get_user", {"preferred_language": preferred_language, "username": username, "password": password})

    def update_user(self, *, preferred_language: Optional[str] = None, username: Optional[str] = None, password: Optional[str] = None, email: Optional[str] = None, email_verification_code: Optional[str] = None, first_name: Optional[str] = None, last_name: Optional[str] = None, nickname: Optional[str] = None, gender: Optional[str] = None, birth_date: Optional[int] = None, phone_number: Optional[str] = None, avatar_id: Optional[str] = None, accept_chatroom_invitation_by_others: Optional[bool] = None) -> Result:
        """Update the signed-in user's profile.

        Args:
            preferred_language: BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
            username: The end-user's username.
            password: The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
            email: See the full parameter reference.
            email_verification_code: See the full parameter reference.
            first_name: See the full parameter reference.
            last_name: See the full parameter reference.
            nickname: See the full parameter reference.
            gender: See the full parameter reference.
            birth_date: See the full parameter reference.
            phone_number: See the full parameter reference.
            avatar_id: See the full parameter reference.
            accept_chatroom_invitation_by_others: See the full parameter reference.

        Returns:
            Result fields: success, error_message.

        Full parameter reference: https://docs.mindupload.app
        """
        return self._request("update_user", {"preferred_language": preferred_language, "username": username, "password": password, "email": email, "email_verification_code": email_verification_code, "first_name": first_name, "last_name": last_name, "nickname": nickname, "gender": gender, "birth_date": birth_date, "phone_number": phone_number, "avatar_id": avatar_id, "accept_chatroom_invitation_by_others": accept_chatroom_invitation_by_others})

